---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: optimus-prime
  labels:
    serviceType: optimus-prime
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      name: optimus-prime
      labels:
        serviceType: optimus-prime
    spec:
      containers:
        - name: optimus-prime
          image: transformers/optimus-prime:latest
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
          - name: JAVA_OPTS
            value: -Xmx64m -Xms64m
          - name: TRANSFORMER_MODE
            valueFrom:
              configMapKeyRef:
                name: autobots-config
                key: transformer.mode
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            timeoutSeconds: 1
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
            initialDelaySeconds: 40
            timeoutSeconds: 1
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: optimus-prime-entrypoint
  namespace: default
spec:
  selector:
    serviceType: optimus-prime
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort